### ISSUE TITLE
A suggestion on balance calculation

### ISSUE THREAD

**Issue by YifanIBBC** [OskarHansson/strvalidator#14]
Hi Dr. OskarHansson,

I'd like to thank you first. I was working on validation work of our STR kits, and I found your package of great help. Thanks a lot!

Only one problem with balance calculation. I'm from China, and we usually define intra-color balance as the lowest peak height divided by the highest peak height within the same dye channel. As far as I know, the US uses the same definition. 

I learned a lot from your code and wrote my own codes to calculate these kind of balance. However, not many researchers in my country are able to create their own functions. So, if you think its a good idea, you may add these kind of functions to your package. And I believe it will be more widely used.

**Comment by OskarHansson** [comment]
Thanks for opening an issue describing your suggestion!

The function should be fairly easy to implement. Unfortunately, I can only spend a small amount of my time developing _strvalidator_. At the moment my highest priority is issue #12 to make the package run in my own workplace.

If you have already created some code to calculate this statistic, you are more than welcome to post it in your repository or here in a comment. You could also make a pull request with your implementation to further speed up development.
