### ISSUE TITLE
New learner with an issue cannot work out

### ISSUE THREAD

**Issue by lewis189** [OskarHansson/strvalidator#17]
Hello there,

I have been learning how to use strvalidator withe the tutorial document and I have hit a problem at section 5.1
I cannot open the Results>Calculate window.
The following image shows the error message in R:
![Result Calculate R error](https://user-images.githubusercontent.com/56836172/67389308-44370e80-f592-11e9-87c0-6d7301997bcb.jpg)

Can you help understand/fix?

Thanks

Lewis

**Comment by OskarHansson** [comment]
Hi Lewis,

The bug appears using the tcltk gui toolkit and is listed under **Known Problems** on the [webpage  ](https://sites.google.com/site/forensicapps/strvalidator#h.p_ID_273). It was fixed in aed8ef6 (developmenet version 2.2.0.9000). 

Install the latest development version to solve the problem. This is done by typing the following line into the command window:
`devtools::install_github("oskarhansson/strvalidator")`

You may need to install devtools to make it work:
`install.packages("devtools", dependencies=TRUE)`

Note that the development version is not stable and some changes may be reverted before the next stable version is released to CRAN (although changes are reverted rarely).

**Comment by lewis189** [comment]
**Hi Oskar

Thanks for help with this.
I tried the install as you said, but for some reason this error comes up:**

> install.packages("devtools", dependencies=TRUE)
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/ANDE/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/devtools_2.2.1.zip'
Content type 'application/zip' length 342956 bytes (334 KB)
downloaded 334 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\ANDE\AppData\Local\Temp\RtmpUteNXk\downloaded_packages
> devtools::install_github("oskarhansson/strvalidator")
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo oskarhansson/strvalidator@master
These packages have more recent versions available.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: digest (0.6.21 -> 0.6.22) [CRAN]
5: rlang  (0.4.0  -> 0.4.1 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
digest (0.6.21 -> 0.6.22) [CRAN]
rlang  (0.4.0  -> 0.4.1 ) [CRAN]
Installing 2 packages: digest, rlang
Installing packages into ‘C:/Users/ANDE/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions are
  later:
       binary source needs_compilation
digest 0.6.21 0.6.22              TRUE
rlang   0.4.0  0.4.1              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/digest_0.6.21.zip'
Content type 'application/zip' length 238213 bytes (232 KB)
downloaded 232 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/rlang_0.4.0.zip'
Content type 'application/zip' length 1091532 bytes (1.0 MB)
downloaded 1.0 MB

package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'strvalidator' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’
>

**Comment by OskarHansson** [comment]
Hi,

Try to download and install Rtools from [http://cran.r-project.org/bin/windows/Rtools/](http://cran.r-project.org/bin/windows/Rtools/)

**Comment by lewis189** [comment]
Hi Oskar

Thanks. I m currently trying this and i will let you know

lewis
