### ISSUE TITLE
Precision plot error

### ISSUE THREAD

**Issue by EricaSalguero** [OskarHansson/strvalidator#21]
Hi,

We are working with 2.4.0 version of the STR Validator software. We are trying to create the Precision analysis plot. But, always we get the same error in R Studio console, and the plot is not generated: 

**Error in !is.null(val_data) && !is.na(val_data): 'lenght =11448' in coercion to 'logical(1)**

![image](https://github.com/OskarHansson/strvalidator/assets/135991513/d07e284c-f96a-42aa-8723-e016e9fd3d7f)

We installed the packages we thing we need. But it is not working.

Thanks for your help

**Comment by OskarHansson** [comment]
Hi,

Thanks for posting the error message. It's difficult to help with this problem without data. Can you post the data, or a minimal example of the data that generates the error, here or to my personal e-mail? A description of the steps performed is also useful.

Kind regards,
Oskar

**Comment by Aksen86** [comment]
Hi Oskar

We have same problem every time we are trying to create any analysis plot. 
Strvalidator  generate files with calculations but we always get the error in R Studio console after cliking on buttom "Save as object" and "save as image".
We were tring to work in different computers but always the same prolem occures. We know that there is no problem with the files couse we chcecked it on  computers of our friends from different lab and we got the alalysis plots.

Eample errors shown by R Studio console:

Error in !is.na(.gData) && !is.null(.gData) : 
  'length = 10530' in coercion to 'logical(1)'

Error in !is.na(.gData) && !is.null(.gData) : 
  'length = 2210' in coercion to 'logical(1)'


Thank you for your help
Aga

**Comment by EricaSalguero** [comment]
Hi Oskar,

We are trying to perform the analysis for an internal validation dataset.
We started with the example files of SureID kit from STR Validator website,
where there is the tutorial to follow the steps for each kind of analysis.
When we upload the file for allele sizing  precision, the stats are
generated correctly and we can export the results. But when we try to get
the plots (any of them), the Rstudio console shows the error that I sent
you. I cannot send you any data, because I am working with your own files
for SureID kit.

Thank you

EricaSalguero

**Comment by OskarHansson** [comment]
@EricaSalguero  and @Aksen86 This is because of R 4.3.0:

_SIGNIFICANT USER-VISIBLE CHANGES
Calling && or || with LHS or (if evaluated) RHS of length greater than one is now always an error, with a report of the form

    'length = 4' in coercion to 'logical(1)'
Environment variable _R_CHECK_LENGTH_1_LOGIC2_ no longer has any effect._

A workaround is to configure RStudio to use an older version of R. That should work. Let me know if it doesn't. I will release a fix on github as soon as I have time to correct the code.

**Comment by Aksen86** [comment]
It works! Than you for your help
Kinder regards
Agnieszka Smoleń

pt., 9 cze 2023, 23:06 użytkownik OskarHansson ***@***.***>
napisał:

**Comment by OskarHansson** [comment]
Should be fixed in version 2.4.1, which will be released to CRAN within a few days.
