### ISSUE TITLE
Column name bug in pull-up analysis

### ISSUE THREAD

**Issue by OskarHansson** [OskarHansson/strvalidator#8]
The bug was found in STR-validator 1.4.0

If there are more than one column name in your dataset that partially match 'Sample' an error message similar to this might appear upon  pull-up analysis:

```
Error in data.frame(Sample.Name = knownSample, Marker = knownMarker, Dye = knownDye, : 
arguments imply differing number of rows: 0, 24
```

A work-around is to use the 'Trim' function to remove any columns in your dataset with a name containing the word 'Sample', except for the column 'Sample.Name'. The analysis should now work.

**Comment by SirHandrake** [comment]
Hi Mr. Hansson,

I am using STR-validator 1.4.0 and I kept getting an error message when I execute Drop-out analysis. I used dataset in csv format and imported them using R studio to convert csv to RData.
The error message says,

"Error in data.frame(Sample.Name = samplesVec, Marker = markersVec, Allele = allelesVec,  :  
arguments imply differing number of rows: 17521, 17601"

I thought this is similar but my dataset does not have the word 'sample' other than Sample.Names.
In addition, when I enter warnings(), I get 50 or more warnings and one of them says,

"50: In calculateDropout(data = .gData, ref = .gRef, threshold = val_threshold, 
... : 
Unhandled combination (dropCount = -1, het = FALSE"
or
dropcount = -2 and het = TRUE.

What do these error messages mean and how can I work around to avoid these errors?

Thank you.

**Comment by OskarHansson** [comment]
Thank you for posting the issue,

Is it possible to send the csv, and RData files to me together with a description of the steps you have performed? Use the maintainer address found at http://cran.r-project.org/web/packages/strvalidator/index.html 

Alternatively provide a reproducible example here (but I know that is not always easy).
